#!/usr/bin/env bash

python3 stub-project.py
mv alternative_date_system repository_template_files
mv buildstub repository_template_files
mv draft-template.md repository_template_files
mv LICENSE repository_template_files
mv names.json repository_template_files
mv pandoc_dependencies repository_template_files
mv quickbuild-template repository_template_files
mv README.md repository_template_files
mv stub-project.py repository_template_files